const actionTypes = Object.freeze({
    //Post
    GET_POST_REQUEST: 'GET_POSTS_REQUEST',
    GET_POST_SUCCESS: 'GET_POST_SUCCESS',
    GET_POST_FAILURE: 'GET_POST_FAILURE',
    CREATE_POST_REQUEST: 'CREATE_POST_REQUEST',
    CREATE_POST_SUCCESS: 'CREATE_POST_SUCCESS',
    CREATE_POST_FAILURE: 'CREATE_POST_FAILURE',
    UPDATE_POST_REQUEST: 'UPDATE_POST_REQUEST',
    UPDATE_POST_SUCCESS: 'UPDATE_POST_SUCCESS',
    UPDATE_POST_FAILURE: 'UPDATE_POST_FAILURE',
    DELETE_POST_REQUEST: 'DELETE_POST_REQUEST',
    DELETE_POST_SUCCESS: 'DELETE_POST_SUCCESS',
    DELETE_POST_FAILURET: 'DELETE_POST_FAILURET',

    // modal
    SHOW_CREATE_POST_MODAL: 'SHOW_CREATE_POST_MODAL',
    HIDE_CREATE_POST_MODAL: 'HIDE_CREATE_POST_MODAL',


})

export default actionTypes;